[package]
name = "fast_matrix_multiplication"
version = "0.1.0"
authors = ["stsoi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
criterion = "0.3.4"
rand = "0.8.4"

[[bench]]
name = "benches"
harness = false
